### ISSUE TITLE
Proposed Standardised "Veracity"

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0261#20]
As counter-intuitive as it might seem, business needs exceed the options provided by a simple boolean, i.e., true or false.  

"Boolean" (upper-case), as defined in some programming languages, supports the notion of nullability, which effectively can mean not-applicable or not yet defined. This closer approximates real-world business needs.

The new element should be of type EnumeratedType with the entries:

TRUE
FALSE
NA (for those cases in which this field is not applicable at all)
UNDEFINED (for those cases in which the value has not yet been determined)

Consumers of this class would define an attribute with this as its type, using a cardinality of 1.

**Comment by AFoletti** [comment]
I like this proposal, mainly for the reason that I dislike nullable attributes. I know they are oftentimes a necessary evil, but a missing value is an ambiguous value (do I not have it but I should, do I not have it because not applicable or I do have it and simply forgot do enter it?).
This proposal removes such ambiguity in a clean way.

**Comment by lars-steffen** [comment]
implemented with #22
